# Generated by Django 4.2.8 on 2023-12-09 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='techonology',
            new_name='technology',
        ),
    ]
